# Первый урок по 2 модулю

## Знакомство с массивами

In [1]:
print("hello Jupyter!")

hello Jupyter!


In [2]:
a = 100
print(a)

100


In [3]:
a

100

In [6]:
a = 10
b = 20

print(a)
print(b)

10
20


In [7]:
%pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 108.9 kB/s eta 0:00:01
     ------------ ------------------------- 20.5/61.0 kB 108.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 100.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 100.9 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.0 kB 115.5 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 147.7 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB 435.7 kB/s eta 0:00:36
   ---------------------------------------- 0.0/15.5 MB 326.8 kB/s eta 0:00:48
   -

In [8]:
# импортирование библиотеки numpy
import numpy as np

- создание массива

In [9]:
# на базе списка

list_1 = (10, 20, 30, 40)

array_1 = np.array(list_1)
array_1

array([10, 20, 30, 40])

In [10]:
list_2 = [10, 20, 3.14]
np.array(list_2)

array([10.  , 20.  ,  3.14])

In [11]:
# создание пустого массива
np.empty(5)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.26070799e-311,
       0.00000000e+000])

In [12]:
# создание массива из нулей
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# создание массива из единиц
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

- 1-мерный массив (вектор-строка)
- 2-мерный массив (вектор-строка матрица)

In [14]:
# 1-мерный массив
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [15]:
# 2-vthysq vfccbd

# вектор-столбец
list_3 = [[10], [20], [30]]
np.array(list_3)

array([[10],
       [20],
       [30]])

In [16]:
# матрица

list_4 = [
    [100,200,300],
    [400,500,600]
]
np.array(list_4)

array([[100, 200, 300],
       [400, 500, 600]])

- Типы данных

In [17]:
arr_0 = np.zeros((3,3))
arr_0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr_0.dtype

dtype('float64')

In [20]:
# конвертация типа данных массива
arr_0.astype("int").dtype

dtype('int32')

In [21]:
arr_0.astype("int8").dtype

dtype('int8')

In [22]:
# создание на базе arange

arr_1 = np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])