In [1]:
import numpy as np

- Генерация массивов со случайными значениями

In [2]:
# 1- мерный массив (вектор-строки) случайных целых значений

arr_0 = np.random.randint(3, size=7)
arr_0

array([1, 0, 1, 2, 2, 2, 0])

In [3]:
np.random.randint(-10, 10, size=10)

array([ -2, -10,   5,   5,  -9,   6,   9,  -9, -10,  -3])

In [5]:
# 2-мерный массив (вектор-столбец) случай целых чисел

arr_1 = np.random.randint(100, size=(7, 1))
arr_1

array([[17],
       [65],
       [83],
       [67],
       [28],
       [77],
       [50]])

In [6]:
# случайное скалярное целых значений 

arr_2 = np.random.randint (100, size=(3, 5))
arr_2

array([[29, 92,  6, 94, 58],
       [98, 21, 84, 19, 92],
       [98, 96, 54, 58, 50]])

In [7]:
# 2 мерный массив (матрица) случайных чисел с плавающей точкой в диапозоне от 0 до 1 

# np.random.rand(3)
# np.random.rand(3,1)
# np.random.rand(3,3)
np.random.rand(3, 3, 3)

array([[[0.4757518 , 0.42640653, 0.90457641],
        [0.81708185, 0.38348465, 0.46071859],
        [0.41855686, 0.80396095, 0.87431633]],

       [[0.70006912, 0.44899664, 0.99672021],
        [0.65063896, 0.6604425 , 0.17119222],
        [0.54034572, 0.42336234, 0.26269403]],

       [[0.3029398 , 0.98890075, 0.83990794],
        [0.3891894 , 0.93061109, 0.56164354],
        [0.76448095, 0.35231378, 0.77055571]]])

In [8]:
# Массив случайных чисел с плавающей точкой 
# из нормального (гауссова) распределения


np.random.rand(3, 3, 3)

array([[[0.64879223, 0.87089238, 0.51868864],
        [0.86740711, 0.14352408, 0.11923422],
        [0.41493676, 0.11317101, 0.27491933]],

       [[0.6230949 , 0.95540815, 0.41734882],
        [0.15858817, 0.34176598, 0.37212045],
        [0.38795343, 0.07544873, 0.8533595 ]],

       [[0.99877498, 0.13811727, 0.2111933 ],
        [0.98051455, 0.59629417, 0.2477587 ],
        [0.68407915, 0.69704663, 0.26686892]]])

In [11]:
np.random.randn(3, 3)

array([[-0.2529688 , -0.00615342,  0.7558624 ],
       [-0.64335698, -0.37274531,  2.39817101],
       [ 0.55499333,  0.46798763, -0.57081801]])

-Атрибуты

In [12]:
# форма массива
arr_0.shape

(7, 1)

In [13]:
# тип данных
arr_0.dtype

dtype('int32')

In [14]:
#  мерность массива (кол-во измерений/осей массива)
arr_0.ndim

2

In [15]:
# объем памяти (в байтах), занимаемый массивом
arr_2.nbytes

60

In [16]:
# кол-во всех элементов массива
arr_2.size

15

- Методы

In [17]:
# конвертация типов данных
arr_2.dtype

dtype('int32')

In [18]:
arr_2.astype("float16")

array([[29., 92.,  6., 94., 58.],
       [98., 21., 84., 19., 92.],
       [98., 96., 54., 58., 50.]], dtype=float16)

In [20]:
# транспонирование - поворот массива по диагонали
#arr_2.transpose()
arr_2.T

array([[29, 98, 98],
       [92, 21, 96],
       [ 6, 84, 54],
       [94, 19, 58],
       [58, 92, 50]])

In [21]:
arr_3 = np.random.rand(3,4)
arr_3

array([[0.80433757, 0.64740397, 0.84678633, 0.77958072],
       [0.55119266, 0.6962734 , 0.6144085 , 0.04711451],
       [0.61634696, 0.13030004, 0.74976586, 0.49267913]])

In [22]:
# минимальное значение 
arr_3.min()

0.0471145142127678

In [24]:
# минимальное значение по определенной оси
arr_3.min(axis=0)

array([0.55119266, 0.13030004, 0.6144085 , 0.04711451])

In [23]:
# максимальное значение
arr_3.max()

0.846786334986028

In [25]:
# среднее значение
arr_3.mean()

0.5813491382195856

In [26]:
arr_0

array([[83],
       [72],
       [39],
       [51],
       [24],
       [31],
       [68]])

In [27]:
# индекс минимального значения
arr_0.argmin()

4

In [28]:
# индекс максимального значения
arr_0.argmax()

0

In [29]:
arr_4 = np.random.randint(10, size=10)
arr_4

array([8, 3, 7, 2, 4, 3, 3, 9, 7, 4])

In [30]:
# сортировка массива
arr_4.sort()

In [31]:
arr_4

array([2, 3, 3, 3, 4, 4, 7, 7, 8, 9])

In [32]:
# переворот массива
arr_4[::-1]

array([9, 8, 7, 7, 4, 4, 3, 3, 3, 2])

- Индексация

In [33]:
arr_5 = np.random.randint(10, size=(3,4))
arr_5

array([[5, 2, 4, 3],
       [6, 7, 5, 1],
       [2, 1, 2, 0]])

In [34]:
# прямая индексация
arr_5[1]

array([6, 7, 5, 1])

In [35]:
# обратная индексация списков и кортежей
arr_5[-1]

array([2, 1, 2, 0])

In [36]:
# извлечение значений элементов массива
# синтаксис списков и кортежей
arr_5[2][2]

2

In [37]:
# синтаксис NumPy
arr_5[2, 2]

2

In [38]:
arr_5[2, 2] = 1000
arr_5

array([[   5,    2,    4,    3],
       [   6,    7,    5,    1],
       [   2,    1, 1000,    0]])

- Срезы

In [39]:
arr_5

array([[   5,    2,    4,    3],
       [   6,    7,    5,    1],
       [   2,    1, 1000,    0]])

In [40]:
# срез строк
arr_5[1:]

array([[   6,    7,    5,    1],
       [   2,    1, 1000,    0]])

In [41]:
# срез столбцов
arr_5[:, 1:]

array([[   2,    4,    3],
       [   7,    5,    1],
       [   1, 1000,    0]])

In [42]:
# срез строк и столбцов
arr_5[:2, 1:]

array([[2, 4, 3],
       [7, 5, 1]])

In [43]:
# срез массива НЕ создает независимый массив,
# а создает представление исходного массива
arr_6 = arr_5[:2, 1:]
arr_6

array([[2, 4, 3],
       [7, 5, 1]])

In [44]:
arr_6[0,0] = 10
arr_6

array([[10,  4,  3],
       [ 7,  5,  1]])

In [45]:
arr_5

array([[   5,   10,    4,    3],
       [   6,    7,    5,    1],
       [   2,    1, 1000,    0]])

In [46]:
# копия массива
arr_7 = arr_5[:2, 1:].copy()
arr_7

array([[10,  4,  3],
       [ 7,  5,  1]])

In [47]:
arr_7[0,0] = 1000
arr_7

array([[1000,    4,    3],
       [   7,    5,    1]])

In [48]:
arr_5

array([[   5,   10,    4,    3],
       [   6,    7,    5,    1],
       [   2,    1, 1000,    0]])

In [49]:
# "зерно" ГПСЧ
np.random.seed(0)

np.random.randint(10, size=5)

array([5, 0, 3, 3, 7])